baseURL: http://example.org/
languageCode: en-us
theme: hugo-PaperMod

params:

  defaultTheme: auto
  disableThemeToggle: false
  assets:
      favicon: "/favicon.ico"
      favicon16x16:  "/favicon-16x16.png"
      favicon32x32:  "/favicon-32x32.png"
      apple_touch_icon:  "/apple-touch-icon.png"
      safari_pinned_tab:  "/safari-pinned-tab.svg"

  profileMode:
      enabled: true
      title: "Hello! This is my portfolio" # optional default will be site title
      subtitle: "This is subtitle"
      imageUrl: "AvatarMaker (1).svg" # optional
      imageTitle: "<title of image as alt>" # optional
      imageWidth: 120 # custom size
      imageHeight: 120 # custom size
      buttons:
        - name: Resume
          url: "/resume/"
        - name: Github
          url: "https://github.com/bakharia"

  socialIcons: # optional
        - name: "Github"
          url: "https://github.com/bakharia"
        - name: "LinkedIn"
          url: "https://linkedin.com/in/bakharia"
        - name: "Tableau"
          url: "https://public.tableau.com/app/profile/bakharia"